### ISSUE TITLE
Mongdb support for raspberry pi?

### ISSUE THREAD

**Issue by jffluis** [Gabisonfire/torrentio-scraper-sh#12]
mongodb The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by Gabisonfire** [comment]
You are likely running this on an arm architecture such as araspberry pie, you'll need to find an image that compatible.

**Comment by purple-emily** [comment]
@jffluis 

```
version: "3.9"

networks:
  mongodb-access:
    name: mongodb-access
    external: true

services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    networks:
      - mongodb-access
    # ports:
    #   - "27017:27017"
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./mnt/mongodb:/data/db
```

Just use the 'official' mongo image
