### ISSUE TITLE
database "torrentio" does not exist

### ISSUE THREAD

**Issue by trulow** [Gabisonfire/torrentio-scraper-sh#5]
I'm getting fatal errors causing the scrapper to consistently restart

Does anyone else have a solution?

```
  original: error: database "torrentio" does not exist

      at Parser.parseErrorMessage (/home/node/app/node_modules/pg-protocol/dist/parser.js:287:98)

      at Parser.handlePacket (/home/node/app/node_modules/pg-protocol/dist/parser.js:126:29)

      at Parser.parse (/home/node/app/node_modules/pg-protocol/dist/parser.js:39:38)

      at Socket.<anonymous> (/home/node/app/node_modules/pg-protocol/dist/index.js:11:42)

      at Socket.emit (node:events:513:28)

      at addChunk (node:internal/streams/readable:315:12)

      at readableAddChunk (node:internal/streams/readable:289:9)

      at Socket.Readable.push (node:internal/streams/readable:228:10)

      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

    length: 94,

    severity: 'FATAL',

    code: '3D000',

    detail: undefined,

    hint: undefined,

    position: undefined,

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'postinit.c',

    line: '885',

    routine: 'InitPostgres'
```

**Comment by trulow** [comment]
After trying removing my initial deployment, I an now getting this error

```
Failed syncing database:  ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 172.18.0.21:5432
    at Client._connectionCallback (/home/node/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)
    at Client._handleErrorWhileConnecting (/home/node/app/node_modules/pg/lib/client.js:327:19)
    at Client._handleErrorEvent (/home/node/app/node_modules/pg/lib/client.js:337:19)
    at Connection.emit (node:events:513:28)
    at Socket.reportStreamError (/home/node/app/node_modules/pg/lib/connection.js:58:12)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  parent: Error: connect ECONNREFUSED 172.18.0.21:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.18.0.21',
    port: 5432
```

Here's my docker compose file

```
version: '3.9'
name: torrentio-self-host

services:
  mongodb:
    container_name: torrentio-mongodb
    restart: unless-stopped
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    networks:
      - torrentio_net
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/bitnami/mongodb
  scraper:
    container_name: torrentio-scraper
    build: ./scraper
    restart: unless-stopped
    networks:
      - torrentio_net
    ports:
      - 7001:7001
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
#      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  torrentio:
    container_name: torrentio
    build: ./addon
    restart: unless-stopped
    networks:
      - torrentio_net
    ports:
      - 7000:7000
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  postgres:
    container_name: torrentio-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - torrentio_net
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio

volumes:
  mongo-data:

networks:
    torrentio_net:
        external: true
        name: torrentio_net
```

**Comment by Gabisonfire** [comment]
Have you tested with the original compose file?

**Comment by trulow** [comment]
> Have you tested with the original compose file?

Yes I did, I used the original compose file during my initial deployment.

**Comment by Gabisonfire** [comment]
I just freshly cloned and ran without an issue. Your second error posted here clearly points to torrentio being unable to reach the postgres DB. Have you tried removing the `networks` instructions see if there's a conflict there?

**Comment by trulow** [comment]
> I just freshly cloned and ran without an issue. Your second error posted here clearly points to torrentio being unable to reach the postgres DB. Have you tried removing the `networks` instructions see if there's a conflict there?

I appreciate your help, I think I was able to solve it. I added the "depends on" variable for the scraper and torrentio although I still get errors with 1337x

Here's my new docker-compose file

```
version: '3.9'
name: torrentio-self-host

services:
  mongodb:
    container_name: torrentio-mongodb
    restart: unless-stopped
    image: docker.io/bitnami/mongodb:7.0
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    networks:
      - torrentio_net
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/bitnami/mongodb
  postgres:
    container_name: torrentio-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - torrentio_net
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio
  scraper:
    container_name: torrentio-scraper
    build: ./scraper
    restart: unless-stopped
    depends_on:
      - mongodb
      - postgres
    networks:
      - torrentio_net
    ports:
      - 7001:7001
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  torrentio:
    container_name: torrentio
    build: ./addon
    restart: unless-stopped
    depends_on:
      - mongodb
      - postgres
    networks:
      - torrentio_net
    ports:
      - 7000:7000
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true

volumes:
  mongo-data:

networks:
    torrentio_net:
        external: true
        name: torrentio_net
```
