### ISSUE TITLE
Enhance logging transports: Loki + Promtail -> Grafana

### ISSUE THREAD

**Issue by iPromKnight** [Gabisonfire/torrentio-scraper-sh#53]
Now #42 has been done, we should expand on this and add a loki transport, or introduce promtail and loki into the metrics stack, as loki can be fed into Grafana now. 

An example we could use for promtail would be 

```yaml
scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'knightcrawler_consumer.*|knightcrawler_addon.*|knightcrawler_producer.*'
        action: keep
```

once #51 is merged in
